version: "3"
services:
  FMA1600_MQTT_Gateway:
    image: docker pull mradziwo/isys_fma1600_mqtt_gateway:latest
    ports:
      - "1883:1883"
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /home/containers/fma1600/config:/config

